stages:
- name: 构建并发布镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bglab-iot/opc-ua-server:v0.1
      pushRemote: true
      registry: 192.168.137.100
- name: 部署OPC UA服务
  steps:
  - applyYamlConfig:
      path: ./opcua-server.yml
timeout: 60
notification: {}
